# Documentation at http://goreleaser.com
project_name: railway

before:
  hooks:
    - go mod download

builds:
  - binary: railway
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X github.com/railwayapp/cli/constants.Version={{.Version}}
    goos:
      - linux
      - windows
      - darwin
      - android
    goarch:
      - amd64
      - arm
      - arm64
      - 386

brews:
  - tap:
      owner: railwayapp
      name: homebrew-railway

    commit_author:
      name: goreleaserbot
      email: goreleaser@railway.app

    homepage: "https://railway.app"
    description: "Develop and deploy code with zero configuration"

    install: |
      bin.install "railway"

snapshot:
  name_template: "{{ .Tag }}"
