# Documentation at http://goreleaser.com
project_name: railway

before:
  hooks:
    - go mod download

builds:
  - binary: railway
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows

  - binary: railway
    ldflags:
      - -s
    env:
      - CGO_ENABLED=1
      - CC=/home/runner/work/osxcross/target/bin/o64-clang
      - CXX=/home/runner/work/osxcross/target/bin/o64-clang++
    goos:
      - darwin

brews:
  - tap:
      owner: railwayapp
      name: homebrew-railway

    commit_author:
      name: goreleaserbot
      email: goreleaser@railway.app

    homepage: "https://railway.app"
    description: "Develop and deploy code with zero configuration"

    install: |
      bin.install "railway"

snapshot:
  name_template: "{{ .Tag }}-next"
