name: Release Label Check

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  label-check:
    runs-on: ubuntu-latest
    steps:
      - uses: NathanielHill/check-pr-label-action@v4.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          valid-labels: "release/patch, release/minor, release/major"
