name: Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish_npm:
    name: Publish Cargo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set version
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Publish
